name: Build Emacs

on:
  workflow_run:
    workflows: [Update Emacs]
    types: [completed]

jobs:
  build-emacs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    - name: Get Current Commit
      run: echo "current_commit=$(grep "(define emacs-master-commit" emacs-master.scm | awk '{print $3}' | cut -c 2-41)" >> $GITHUB_ENV
    - name: Get Source Commit
      run: echo "source_commit=$(curl -s https://api.github.com/repos/emacs-mirror/emacs/commits/master | jq -r '.sha')" >> $GITHUB_ENV
    - name: Compare Commits
      id: compare-commits
      run: |
        if [ "${{env.source_commit }}" != "${{ env.current_commit }}" ]; then
          echo "The commits are different. Continue the workflow."
          echo "different_commit='true'" >> $GITHUB_OUTPUT
        else
          echo "The commits are the same. Exiting the workflow..."
          echo "different_commit='false'" >> $GITHUB_OUTPUT
        fi
    - name: Install Guix
      if: ${{ contains(steps.compare-commits.Outputs.different_commit, 'true') }}
      uses: PromyLOPh/guix-install-action@40615e98e5c16a451aec10fe01c214ed07cbaa77
      with:
        channels: |-
          (cons* (channel
                  (name 'emacs-master)
                  (url "https://github.com/gs-101/emacs-master.git")
                  (branch "main")
                  (introduction
                   (make-channel-introduction
                    "568579841d0ca41a9d222a2cfcad9a7367f9073b"
                    (openpgp-fingerprint
                     "3049 BF6C 0829 94E4 38ED  4A15 3033 E0E9 F7E2 5FE4"))))
                 %default-channels)
    - name: Build Emacs
      if: ${{ contains(steps.compare-commits.Outputs.different_commit, 'true') }}
      run: guix build emacs-master --fallback
