name: Build Emacs

on:
  push

jobs:
  build-emacs:
    runs-on: ubuntu-latest
    steps:
    - name: Guix Cache
      uses: actions/cache@v4.2.0
      with:
        path: ~/.cache/guix
        # Use a key that (almost) never matches
        key: guix-cache-${{ github.sha }}
        restore-keys: |
          guix-cache-
    - name: Install Guix
      uses: PromyLOPh/guix-install-action@v1.5
      with:
        channels: |-
          (cons* (channel
                  (name 'emacs-master)
                  (url "https://github.com/gs-101/emacs-master.git")
                  (branch "main")
                  (introduction
                   (make-channel-introduction
                    "568579841d0ca41a9d222a2cfcad9a7367f9073b"
                    (openpgp-fingerprint
                     "3049 BF6C 0829 94E4 38ED  4A15 3033 E0E9 F7E2 5FE4"))))
                 %default-channels)
    - name: Build Emacs
      run: guix build emacs-master --fallback
