name: Build Emacs

jobs:
  build-emacs:
    runs-on: ubuntu-latest
    steps:
    - name: Install Guix
      uses: PromyLOPh/guix-install-action@28ffda077fe9b9f0c94d79ac2c7ea9aad8d6cf46
      with:
        channels: |-
          (cons* (channel
                  (name 'emacs-master)
                  (url "https://github.com/gs-101/emacs-master.git")
                  (branch "main")
                  (introduction
                   (make-channel-introduction
                    "568579841d0ca41a9d222a2cfcad9a7367f9073b"
                    (openpgp-fingerprint
                     "3049 BF6C 0829 94E4 38ED  4A15 3033 E0E9 F7E2 5FE4"))))
                 %default-channels)
    - name: Build Emacs
      run: guix build emacs-master --fallback
