name: Build Emacs

on:
  push

jobs:
  build-emacs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: ~/.cache/guix
        key: ${{ runner.os }}-guix
    - name: Install Guix
      uses: gs-101/guix-install-action@0daecea5bda09e7a5034a74419003f110deae22a
      with:
        channels: |-
          (cons* (channel
                  (name 'emacs-master)
                  (url "https://github.com/gs-101/emacs-master.git")
                  (branch "main")
                  (introduction
                   (make-channel-introduction
                    "568579841d0ca41a9d222a2cfcad9a7367f9073b"
                    (openpgp-fingerprint
                     "3049 BF6C 0829 94E4 38ED  4A15 3033 E0E9 F7E2 5FE4"))))
                 %default-channels)
    - name: Build Emacs
      run: guix build emacs-master --fallback
