name: Update Emacs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-emacs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl grep guix git gpg guile-3.0 guile-library
    - name: Get Current Commit
      run: |
        echo "current-commit=$(grep "(define emacs-master-commit" emacs-master.scm | awk '{print $3}' | cut -c 2-41)" >> $GITHUB_ENV
    - name: Update Emacs
      run: |
        chmod +x bin/get_hash.sh
        chmod +x bin/update-emacs
        bin/update-emacs
        echo "new-commit=$(grep "(define emacs-master-commit" emacs-master.scm | awk '{print $3}' | cut -c 2-41)" >> $GITHUB_ENV
    - name: Compare Commits
      id: compare-commits
      run: |
        if [ "${{ env.new-commit }}" != "${{ env.current-commit }}" ]; then
          echo "The commits are different. Continue the workflow."
          echo "different-commit='true'" >> $GITHUB_OUTPUT
        else
          echo "The commits are the same. Exiting the workflow..."
          echo "different-commit='false'" >> $GITHUB_OUTPUT
        fi
    - name: Import GPG Key
      if: ${{ contains(steps.compare-commits.Outputs.different-commit, 'true') }}
      run: echo "$GPG_KEY" | base64 --decode | gpg --batch --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
    - name: Custom GPG Signing Program
      if: ${{ contains(steps.compare-commits.Outputs.different-commit, 'true') }}
      run: |
        echo "#!/bin/bash" >> /tmp/gpg.sh
        echo "gpg --batch --pinentry-mode=loopback --passphrase \$GPG_KEY_PASSPHRASE \"\$@\"" >> /tmp/gpg.sh
        chmod +x /tmp/gpg.sh
      env:
        GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
    - name: Setup Git
      if: ${{ contains(steps.compare-commits.Outputs.different-commit, 'true') }}
      run: |
        git config commit.gpgsign true
        git config user.signingkey $GPG_KEY_ID
        git config gpg.program /tmp/gpg.sh
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
    - name: Commit
      if: ${{ contains(steps.compare-commits.Outputs.different-commit, 'true') }}
      run: |
        git add emacs-master.scm
        short_commit=$(grep "(define emacs-master-commit" emacs-master.scm | awk '{print $3}' | cut -c 2-10)
        git commit -m "feat (emacs-master.scm): Update Emacs to $short_commit" --gpg-sign=$GPG_KEY_ID
        git push --set-upstream origin main
      env:
       GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
       GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
       GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
       GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
       GIT_AUTHOR_NAME: github-actions
       GIT_AUTHOR_EMAIL: github-actions@example.com
